policies:
  - name: a-firehose-delivery-stream-encryption-sse-configured
    description: |
      Account {account_id} - Ensure AWS Kinesis Data Firehose delivery stream with Direct PUT and other sources as source has Server-side encryption configured
    resource: firehose
    filters:
      - and:
        - type: value
          key: DeliveryStreamEncryptionConfiguration.Status
          value: DISABLED
          op: equal
        - type: value
          key: DeliveryStreamType
          value: DirectPut
          op: equal
    actions:
      - type: webhook
        url: REPLACE_WEBHOOK_HERE
        body: |-
          {
             "attachments": [
               {
                 "fallback": `CloudCustodian Policy Violation`,
                 "title": policy.description,
                 "color": `danger`,
                 "fields": [
                   {
                     "title": `Priority`,
                     "value": `High`,
                     "short": `true`
                   },
                   {
                     "title": `Kinesis Delivery Stream Name`,
                     "value": resource.DeliveryStreamName,
                     "short": `true`
                   },
                   {
                     "title": `Delivery Stream Encryption Status`,
                     "value": resource.DeliveryStreamEncryptionConfiguration.Status,
                     "short": `true`
                   },
                   {
                     "title": `Account ID`,
                     "value": account_id,
                     "short": `true`
                   },
                   {
                     "title": `Region`,
                     "value": region,
                     "short": `true`
                   }
                 ],
                 "footer": `Powered By CldCvr DevSecOps`,
                 "footer_icon": `https://a.cldcvr.com/cldcvr/favicons/64px.png`
               }
             ]
          }